#!/usr/bin/env bash
FILE=$(mktemp -q -t emphasize.XXXXXX)
echo "$*" > $FILE
if read -t 0 ; then
	cat >> $FILE
fi
kitty +kitten panel --lines 60 sh -c "printf \"\n\n\n\n\n\" ; cat $FILE ; sleep 5s; read"
cat $FILE
rm $FILE
