#!/usr/bin/env bash
if [ -e /System ]
then
  /System/Library/PrivateFrameworks/Apple80211.framework/Versions/Current/Resources/airport -I | awk '/ SSID/ {print substr($0, index($0, $2))}'
else
  iwconfig 2>/dev/null | grep ESSID | cut -d: -f2 | sed -e 's/"//g'
fi
