#!/usr/bin/python
# here lies the greatest hack of my life
# may the Lord have mercy on its soul.
# (used to compile gfsvc's unf_ext and eventmachine)
"""
1. rename this to g++
2. put this in your path
3. make sure this is executable
4. sudo mv /usr/bin/g++ /usr/bin/g+++
5. go to gfsvc root
6. bundle install
7. sudo mv /usr/bin/g+++ /usr/bin/g++
8. pretend this never happened.
"""
import sys
import subprocess

args = sys.argv[:]

if "-Wshorten-64-to-32" in args:
    args.remove("-Wshorten-64-to-32")
    
args[0] = "g+++"
subprocess.call(args)

