#!/usr/bin/env bash


case "$1" in
    -h|--help)
echo -e "lsuser
usage:
\t--short\t-s\tList users who have /home listed in /etc/passwd (default)
\t--home\t\tls /home
\t--all\t-a\tall of the users.
\t--help\t-h\tThis menu."
	;;
    -a|--all)
	  cat /etc/passwd | cut -d: -f1
	;;
    --home)
	  ls /home
	;;
    -s|--short|""|*)
	  cat /etc/passwd | grep "/home" |cut -d: -f1
	;;
esac

