#!/usr/bin/env bash

for FILE in "$@"
do
	if [ -f "$FILE" ] ; then
		case "$FILE" in
			*.tar.bz2) tar -jtvf "$FILE" ;;
			*.tar.gz) tar -ztvf "$FILE" ;;
			*.bz2) bz2 - "$FILE" ;;
			*.rar) unrar lb "$FILE" ;;
			*.gz) gunzip --list "$FILE" ;;
			*.tar) tar -tvf  "$FILE" ;;
			*.tbz2) tar -jtvf "$FILE" ;;
			*.tgz) tar -ztvf "$FILE" ;;
			*.zip) unzip -l "$FILE" ;;
			*.Z) gunzip --list "$FILE" ;;
			*.7z) 7z l "$FILE" ;;
			*) echo "'$FILE' cannot be listed via lszip" ;;
		esac
	else
		echo "'$FILE' is not a valid file"
	fi
done
