#!/usr/bin/env bash
#	ROOT_DIR="."
#	if [[ ! -z "$1" ]]
#	then
#		ROOT_DIR="$1"
#	fi
#	echo "Starting in $ROOT_DIR"

set +H
find . -type f \
  -iname '*.mov' \
	-o -iname '*.avi' \
	-exec sh -c '
for FILE do
	echo "PROCESSING $FILE"
	DIRNAME=$(dirname "$FILE")
	BASENAME=$(basename "$FILE")
	mkdir -p "${DIRNAME}/caps"
	avconv -i "$FILE" -vsync 1 -r 1 -an -y "${DIRNAME}/caps/${BASENAME}-image-%5d.jpg"
done
' sh {} +

