#!/usr/bin/env bash

function get_speed {
  R1=`cat /sys/class/net/$INTERFACE/statistics/rx_bytes`
  T1=`cat /sys/class/net/$INTERFACE/statistics/tx_bytes`
  sleep 1
  R2=`cat /sys/class/net/$INTERFACE/statistics/rx_bytes`
  T2=`cat /sys/class/net/$INTERFACE/statistics/tx_bytes`
  TBPS=`expr $T2 - $T1`
  RBPS=`expr $R2 - $R1`
  TKBPS=`expr $TBPS / 1024`
  RKBPS=`expr $RBPS / 1024`
  echo "$INTERFACE: U:$TKBPS kb/s D:$RKBPS kb/s"
}

if [[ -z "$1" ]] || [[ "$1" == "--default" ]]
then
    INTERFACE="$(/sbin/route -n | grep '^0.0.0.0' | head -n 1 | rev | cut -d' ' -f1 | rev)"
else
    INTERFACE="$1"
fi


if [[ "$2" == "--watch" ]]
then
	while true
	do
		get_speed "$INTERFACE"
	done
else
	get_speed "$INTERFACE"
fi




