#!/usr/bin/env bash
if [[ -z "$1" ]] 
then
	echo -n "Script name: "
  read SCRIPT
else
	SCRIPT="$1"
fi
if [ -e $SCRIPTS_DIR/$SCRIPT ]
then
	vim + $SCRIPTS_DIR/$SCRIPT
else
echo -e "#!/usr/bin/env bash\n\n" >> $SCRIPTS_DIR/$SCRIPT && vim + $SCRIPTS_DIR/$SCRIPT && chmod +x $SCRIPTS_DIR/$SCRIPT

fi


