#!/usr/bin/env bash
# -e all processes
# -o format
# r  only runningi


CMD="ucmd"

if [[ "$1" == "-l" ]] || [[ "$1" == "--long" ]]
then
	CMD="args"
	shift
fi

# mac doesn't know about ucmd
if [[ "$(uname)" == "Darwin" ]]
then
	CMD="args"
fi


ARGS="$@"
if [[ -z $ARGS ]]
then
    ARGS='.'
fi


RESULTS=$(ps -e -o "pid,%cpu,%mem,$CMD" | grep $ARGS )
if [[ "$RESULTS" ]]
then
   if [[ ! "$ARGS" == "." ]]
   then
       echo  "  PID %CPU %MEM CMD"
   fi

   echo "$RESULTS"
else
    exit 1
fi
