#!/usr/bin/env bash
# -e all processes
# -o format
# r  only runningi
ARGS="$@"
if [[ -z $ARGS ]]
then
    ARGS='.'
fi

RESULTS=$(ps -e -o "pid,%cpu,%mem,ucmd" | grep $ARGS )
if [[ "$RESULTS" ]]
then
   if [[ ! "$ARGS" == "." ]]
   then
       echo  "  PID %CPU %MEM CMD"
   fi

   echo "$RESULTS"
else
    exit 1
fi
