#!/usr/bin/env bash
# -e all processes
# -o format
# r  only runningi
# T only in this terminal

CMD="ucmd"

if [[ "$1" == "-l" ]] || [[ "$1" == "--long" ]]
then
	CMD="args"
	shift
fi


ARGS="$@"
if [[ -z $ARGS ]]
then
    ARGS='.'
fi

RESULTS=$(ps T -o "pid,%cpu,%mem,$CMD" | grep $ARGS )
if [[ "$RESULTS" ]]
then
   if [[ ! "$ARGS" == "." ]]
   then 
       echo "  PID %CPU %MEM CMD"
   fi
   echo "$RESULTS"
else
    exit 1
fi
