#!/usr/bin/env bash
# sudo apt-get update ; sudo apt-get install

CURRDIR=$(pwd)

function update_machines {
    
    if [[ -z "$PERS_DIR" ]]
    then
        PERS_DIR="$HOME/pers"
    fi
    
    if [[ -d $PERS_DIR/machines      ]] &&
       [[ -d $PERS_DIR/machines/.git ]]
    then
      echo "Updating machines repository."
      cd $PERS_DIR/machines
      git pull --no-edit origin master
    else
      echo "No machines repository found.  Cloning."
      git clone git@bitbucket.org:swirepe/machines.git $PERS_DIR/machines
    fi
    
    
    SAGIRECORD_DIR="$PERS_DIR/machines/apt/$(hostname)"
    
    
    
    if [ ! -d $SAGIRECORD_DIR ]
    then
        echo "[sagi] $SAGIRECORD_DIR does not exist: creating."
        mkdir -p $SAGIRECORD_DIR
fi

}

NON_ARG_PACKAGE="false"
for package in $@
do
    if [[ "$package" == "-"* ]]
		then
        packages+=($package)
    elif ! dpkg -s $package &> /dev/null
    then
        packages+=($package)
        NON_ARG_PACKAGE="true"
    else
        echo "Warning: Package already installed: $package" >/dev/stderr
    fi        
done


if [ ${#packages[@]} = 0 ]
then
    echo "Nothing to install. Exiting."
    exit 0
elif [[ $NON_ARG_PACKAGE == "false" ]]
then
    echo "Only arguments remaining: $packages"
    echo "Exiting."
    exit 0
else
    echo "Installing packages: $packages"
fi



sudo apt-get update

sudo apt-get install $packages && ( 
    update_machines &&
    cd "$SAGIRECORD_DIR" &&
    dpkg --get-selections > aptlist.txt &&
    git add aptlist.txt &&
    git commit -m "sagi $(hostname) $*" &&
    git push origin master
)
        
cd "$CURRDIR"
    
