#!/usr/bin/env bash
# sudo apt-get update ; sudo apt-fast install -y


# if apt-fast isn't installed, install it
if [[ -z "$(which apt-fast)" ]]
then
    echo "[sagify] apt-fast not installed: installing."
    sudo add-apt-repository ppa:apt-fast/stable
    sagi apt-fast
fi


CURRDIR=$(pwd)

function update_machines {

    if [[ -z "$PERS_DIR" ]]
    then
        PERS_DIR="$HOME/pers"
    fi
    
    if [[ -d $PERS_DIR/machines ]]
    then
      echo "Updating machines repository."
      cd $PERS_DIR/machines
      git pull --no-edit origin master
    else
      echo "No machines repository found.  Cloning."
      git clone git@bitbucket.org:swirepe/machines.git $PERS_DIR/machines
    fi
    
    
    SAGIRECORD_DIR="$PERS_DIR/machines/apt/$(hostname)"
    
    if [ ! -d $SAGIRECORD_DIR ]
    then
        echo "[sagi] $SAGIRECORD_DIR does not exist: creating."
        mkdir -p $SAGIRECORD_DIR
    fi

}

for package in $@
do
    if [[ "$package" == "-"* ]] || ! dpkg -s $package &> /dev/null
    then
        packages+=($package)
    else
        echo "Warning: Package already installed: $package" >/dev/stderr
    fi        
done

if [ ${#packages[@]} = 0 ]
then
    echo "Nothing to install. Exiting."
    exit 0
else
    echo "Installing packages: ${#packages[@]}"
fi



sudo apt-fast update

sudo apt-fast install -y ${packages[@]} && ( 
    update_machines &&
    cd "$SAGIRECORD_DIR" &&
    dpkg --get-selections > aptlist.txt &&
    git add aptlist.txt &&
    git commit -m "sagify $(hostname) $*" &&
    git push origin master
)
        
cd "$CURRDIR"
    
