#!/usr/bin/python

import shlex
import subprocess
import sys


if len(sys.argv) == 1:
    print """xpipe
    This program tries each of the commands passed to it with the last
    argument, only going on to the next one if the one preceeding it returned a 
    non-zero exit status or printed nothing.
    """
    sys.exit(0)


cmds = sys.argv[1:]
retcode = 1

try:
    while True:
        inline = raw_input()
        for cmd in cmds:
            cmd = shlex.split(cmd)
            cmd.append(inline)
            
            
            proc = subprocess.Popen(cmd, stdout = subprocess.PIPE, stderr= subprocess.PIPE)
            output,error = proc.communicate()
            retcode = proc.wait()
            """
            print "-------------"
            print "cmd", cmd
            print "inline", inline
            print "output", output
            print "-------------"
            """
            sys.stderr.write(error)    
            if output.lstrip().rstrip() != '':
                subprocess.call(cmd)  # rerun it.  oh man.
                break
                #sys.stdout.write(output)
                
except EOFError:
    pass


sys.exit(retcode)

