#!/usr/bin/env bash

if [[ "$1" == "--help" ]]
then
    echo -e "$(basename $0)"
    echo -e "    Peter Swire - swirepe.com"
    echo -e "    Part of a suite of command line tools for manipulating transmission."
    $0 --help-oneline
    exit 0    
fi

if [[ "$1" == "--help-oneline" ]]
then
    echo -e "$(basename $0) <command>\tA wrapper for other commands. Try 'bt commands'"
    exit 0
fi

CMD_PART="$1"
CMD="bt$CMD_PART"
shift
if [[ $(which $CMD) == "" ]]
then
	echo "ERROR: bt $CMD_PART not a command." > /dev/stderr
  exit 1
else
	$CMD $@
fi
