#!/usr/bin/env bash

if [[ "$1" == "--help" ]]
then
    echo -e "$(basename $0)"
    echo -e "    Peter Swire - swirepe.com"
    echo -e "    Part of a suite of command line tools for manipulating transmission."
    $0 --help-oneline
    exit 0    
fi

if [[ "$1" == "--help-oneline" ]]
then
    echo -e "$(basename $0) <ids>\tList all available bittorrent commands."
    exit 0
fi


CMD_PATH="$(dirname $0)"
PREFIX=$(basename $0 | sed s/commands$//)

( for CMD in $(find -L $CMD_PATH -executable -type f -name $PREFIX'*' | sort)
do
    $CMD --help-oneline | sed "s/^$PREFIX/$PREFIX /"
done ) | column -s $'\t' -t
