#!/usr/bin/env bash

if [[ "$1" == "--help" ]]
then
    echo -e "$(basename $0)"
    echo -e "    Peter Swire - swirepe.com"
    echo -e "    Part of a suite of command line tools for manipulating transmission."
    $0 --help-oneline
    exit 0    
fi

if [[ "$1" == "--help-oneline" ]]
then
    echo -e "$(basename $0) <id>\tExits 0 if torrent is done, 1 otherwise."
    exit 0
fi


TORRENT_ID="$1"

if [[ -z "$TORRENT_ID" ]]
then
    echo "Usage: btdone torrent_id" > /dev/stderr
    echo "   Exits 0 if done, 1 otherwise." > /dev/stderr
    exit 0
fi


STATUS=$(btinfo $TORRENT_ID | grep "Percent Done: 100%")

if [[ -z "$STATUS" ]] 
then
    exit 1
else
    exit 0
fi
