#!/usr/bin/env bash

TORRENT_ID="$1"

if [[ -z "$TORRENT_ID" ]]
then
    echo "Usage: btdone torrent_id" > /dev/stderr
    echo "   Exits 0 if done, 1 otherwise." > /dev/stderr
    exit 0
fi


STATUS=$(btinfo $TORRENT_ID | grep "Percent Done: 100%")

if [[ -z "$STATUS" ]] 
then
    exit 1
else
    exit 0
fi
