#!/usr/bin/env bash
if [[ "$1" == "--help" ]]
then
    echo -e "$(basename $0)"
    echo -e "    Peter Swire - swirepe.com"
    echo -e "    Part of a suite of command line tools for manipulating transmission."
    $0 --help-oneline
    exit 0    
fi

if [[ "$1" == "--help-oneline" ]]
then
    echo -e "$(basename $0) <ids>\tRetrieve information on selected torrents."
    exit 0
fi


if [ -e $HOME/.btrc ]
then
    source $HOME/.btrc
else
    echo "Using defaults for snake." > /dev/stderr
    BT_HOST="snake"
    BT_AUTH="admin:snake"
fi


if [[ -z "$1" ]]
then
    transmission-remote $BT_HOST --auth $BT_AUTH --session-info
else
    for TORRENT_ID in $@
    do
        transmission-remote $BT_HOST --auth $BT_AUTH -t $TORRENT_ID --info
    done
fi
