#!/usr/bin/env bash
if [[ "$1" == "--help" ]]
then
    echo -e "$(basename $0)"
    echo -e "    Peter Swire - swirepe.com"
    echo -e "    Part of a suite of command line tools for manipulating transmission."
    $0 --help-oneline
    exit 0    
fi

if [[ "$1" == "--help-oneline" ]]
then
    echo -e "$(basename $0) <id>\tRetrieve the name of selected torrent."
    exit 0
fi


TORRENT_ID="$1"
btinfo $TORRENT_ID | grep Name: | sed 's/.*Name: //'


