#!/usr/bin/env bash

if [ -e $HOME/.btrc ]
then
    source $HOME/.btrc
else
    echo "Using defaults for snake." > /dev/stderr
    BT_HOST="snake"
    BT_AUTH="admin:snake"
fi


TORRENT_ID="$1"
DESTINATION="$2"

if [[ -z "$TORRENT_ID" ]]
then
    echo "Usage: btpull torrent_id destination" > /dev/stderr
    exit 0
fi

if [[ -z "$DESTINATION" ]]
then
    DESTINATION="."
fi

found="false"
complete=""
while read torrent 
do
    if [[ "$TORRENT_ID" == $(echo $torrent | awk '{print $1}') ]]
    then
        found="true"
        echo "Fetching $torrent"

        complete=$(btcomplete $torrent )
    fi
done <  <(btid)
  

if [[ "$found" == "false" ]]
then
    echo "Available torrents:" > /dev/stderr
    lstorrents > /dev/stderr
    echo "Error: Torrent ID not found: $TORRENT_ID" > /dev/stderr
    exit 1
fi


if [[ "100%" != "$complete" ]]
then
    echo "Error: Torrent ID  $TORRENT_ID is not complete: $complete" > /dev/stderr
    exit 2
fi

LOCATION=$(transmission-remote $BT_HOST --auth $BT_AUTH -t $TORRENT_ID -i | grep Location | awk '{print $2}')

if [[ -z "$LOCATION" ]]
then
    echo "Error finding location of $TORRENT_ID" > /dev/stderr
    exit 3
fi

echo "Torrent found in location $LOCATION" > /dev/stderr


NAME_COL_OFFSET=$(transmission-remote $BT_HOST --auth $BT_AUTH  -t $TORRENT_ID --files  | grep Name | sed 's/Name.*//' | wc -c)

function rsync_die {
    echo "Error rsyncing $1 to $2" > /dev/stderr
    exit 1
}

DESTINATION="'$DESTINATION/$(btname $TORRENT_ID)'"
mkdir -p "$DESTINATION"

BT_USER=$(echo $BT_AUTH | cut -d: -f1)
BT_PASS=$(echo $BT_AUTH | cut -d: -f2)

while read remote_file 
do
    remote_file="root@snake:${LOCATION}/${remote_file}"
    remote_file=$(echo "$remote_file" | sed 's/ /\\ /g')
    echo "Pulling $remote_file" > /dev/stderr
    rsync_retry --rsh="/usr/bin/sshpass -p $BT_PASS ssh -o StrictHostKeyChecking=no -l $BT_USER" --archive --compress --progress --partial "$remote_file" "$DESTINATION" || rsync_die "$remote_file" "$DESTINATION"
done < <(transmission-remote $BT_HOST --auth $BT_AUTH  -t $TORRENT_ID --files  | tail -n +3 | cut -c"$NAME_COL_OFFSET"- )

