#!/usr/bin/env bash

# remote a torrent and delete its content on disk

if [ -e $HOME/.btrc ]
then
    source $HOME/.btrc
else
    echo "Using defaults for snake." > /dev/stderr
    BT_HOST="snake"
    BT_AUTH="admin:snake"
fi


TORRENT_ID="$1"

transmission-remote $BT_HOST --auth $BT_AUTH -t $TORRENT_ID --remove-and-delete
